services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - ${MYSQL_LOCAL_PORT}:3306
    volumes:
      - db:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d:ro

  adminer:
    image: adminer
    profiles:
      - adminer
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
      - ADMINER_DESIGN=${ADMINER_DESIGN}
    ports:
      - ${ADMINER_LOCAL_PORT}:8080
    depends_on:
      - mysql

  webproxy:
    image: nginx
    environment:
      - WEBAPP_HOST=webapp
      - WEBAPP_PORT=5645
      - HTTP_PORT=80
      - WWW_ROOT=/var/www/snapcamera
    volumes:
      - ./ssl/studio-app.snapchat.com.crt:/etc/ssl/certs/studio-app.snapchat.com.crt:ro
      - ./ssl/studio-app.snapchat.com.key:/etc/ssl/private/studio-app.snapchat.com.key:ro
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/theme:/etc/nginx/theme:ro
      - ./nginx/snap-camera-categories-media:/var/www/snapcamera/snap-camera-categories-media:ro
      - ./nginx/snap-camera-media:/var/www/snapcamera/snap-camera-media:ro
      - ./nginx/snap-camera-media-alt:/var/www/snapcamera/snap-camera-media-alt:ro
      - ./import:/var/www/snapcamera/import
      - storage:/var/www/snapcamera
    ports:
      - ${NGINX_LOCAL_PORT}:80
      - 443:443
    depends_on:
      - webapp

  webapp:
    build: .
    environment:
      - DB_HOST=mysql
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_PORT=3306
      - PORT=5645
      - BRIDGE_ADDR=ws://camera-kit-bridge:3000
      - BRIDGE_API_TOKEN=${BRIDGE_API_TOKEN}
      - STORAGE_PATH=/var/lib/snapcamera
      - IMPORT_DIR=import
      - MEDIA_DIR=snap-camera-media
      - MEDIA_DIR_ALT=snap-camera-media-alt
      # the storage server url will be served to the snap camera application
      # it must be reachable from your local network
      - STORAGE_SERVER=http://studio-app.snapchat.com:${NGINX_LOCAL_PORT}
    volumes:
      # content of snap-camera-media (MEDIA_DIR) is not getting included automatically through storage
      - ./nginx/snap-camera-media:/var/lib/snapcamera/snap-camera-media:ro
      - ./import:/var/lib/snapcamera/import
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - storage:/var/lib/snapcamera
    ports:
      - ${APP_LOCAL_PORT}:5645
    depends_on:
      - mysql

  camera-kit-bridge:
    image: ptrumpis/snap-camerakit-bridge@sha256:2db205698617ca279548f9f327e3ebfc603af033aafe1dbcd4e770f8f1d25eeb
    profiles:
      - creator
    ports:
      - ${BRIDGE_LOCAL_PORT}:3000
    depends_on:
      - webapp

volumes:
  storage:
    name: server-storage
  db:
    name: mysql-db
