blank_issues_enabled: false
contact_links:
  - name: ğŸ“· Report non-working Lenses
    url: https://github.com/ptrumpis/snap-camera-server/discussions/8
    about: List of incompatible Lenses
  - name: ğŸ™ Ask the community for help
    url: https://github.com/ptrumpis/snap-camera-server/discussions/categories/q-a
    about: Please ask general questions here, there may already be an answer to your question.
  - name: ğŸ“˜ Wiki
    url: https://github.com/ptrumpis/snap-camera-server/wiki
    about: In the wiki you will find many solutions to problems and background information.
  - name: ğŸ’¬ Discussions
    url: https://github.com/ptrumpis/snap-camera-server/discussions
    about: Join Discussions and find answers to common problems.